# Copyright 2019 The ANGLE Project Authors.
# Habilita build estático para o ANGLE

# Força linking estático
angle_static_linking = true
angle_use_static_angle = true

# Configuração para exportar símbolos corretamente em builds estáticos
config("angle_static_config") {
  defines = [
    "ANGLE_EXPORT=",
    "ANGLE_STATIC=1",
    "ANGLE_UTIL_EXPORT=",
    "EGLAPI=",
    "GL_APICALL=",
    "GL_API=",
  ]
}
